### ISSUE TITLE
Tagbot Error

### ISSUE THREAD

**Issue by FelixArgyle** [Sven65/TagBot#8]
Error -
```js
TypeError: Cannot read property 'toUTCString' of null
    at TagHandler.getSendersMemberVariables (/home/mackan/tagbot/src/Handlers/Tags/Tags.js:22:38)
    at TagHandler.Handle (/home/mackan/tagbot/src/Handlers/Tags/Tags.js:168:9)
    at Promise.all.then.values (/home/mackan/tagbot/src/Handlers/messageCreate.js:121:20)
```
Some Context on what threw the error
![08eb2a](https://user-images.githubusercontent.com/12903523/53097468-d9e25000-3564-11e9-863f-cab3855152e0.png)

This seems to only happen to a small number of users.

**Comment by Willard21** [comment]
Sometimes new guild members aren't added to the member cache. Seems to be a Discord.js bug. It caused problems with username updates in DRPG too. The fix was to fetch the user from the API if they weren't in the cache.
